version: '2'

services:
  spark:
    image: docker.io/bitnami/spark:3
    hostname: spark
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
        - ./app:/usr/local/spark/app
        - ./resources:/usr/local/spark/resources
        - ../datalake:/usr/local/datalake

    ports:
      - "8181:8080"
      - "7077:7077"
    networks:
      - proxynet

  spark-worker:
    image: docker.io/bitnami/spark:3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
        - ./app:/usr/local/spark/app
        - ./resources:/usr/local/spark/resources
        - ../datalake:/usr/local/datalake

    networks:
      - proxynet

networks:
    proxynet: